# Generated by Django 4.2.9 on 2024-02-08 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0002_application_applicationdefault'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicationdefault',
            name='application',
            field=models.IntegerField(default=1),
        ),
    ]
