# Generated by Django 5.0.4 on 2024-08-09 09:33

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0003_alter_applicationdefault_application'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'managed': True},
        ),
        migrations.CreateModel(
            name='CandidateDetails',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(blank=True, max_length=45, null=True)),
                ('middle_name', models.CharField(blank=True, max_length=45, null=True)),
                ('last_name', models.CharField(blank=True, max_length=45, null=True)),
                ('candidate_name', models.CharField(blank=True, max_length=191, null=True)),
                ('country_code', models.CharField(default='+91', max_length=4, validators=[django.core.validators.RegexValidator(message="Country code must be in the format '+123'.", regex='^\\+\\d{1,3}$')])),
                ('mobile_no', models.CharField(max_length=11, validators=[django.core.validators.RegexValidator(message='mobile_no number must be between 4 and 11 digits.', regex='^\\d{4,11}$')])),
                ('email', models.EmailField(max_length=254)),
                ('application_id', models.IntegerField(default=1)),
                ('pan_no', models.CharField(blank=True, max_length=6, null=True)),
                ('aadharcard_number', models.IntegerField(blank=True, null=True)),
                ('skill_set', models.CharField(blank=True, max_length=445, null=True)),
                ('gender', models.IntegerField(blank=True, null=True)),
                ('current_organization', models.CharField(blank=True, max_length=90, null=True)),
                ('current_designation', models.CharField(blank=True, max_length=90, null=True)),
                ('ovarall_experiance', models.CharField(blank=True, max_length=90, null=True)),
                ('relevant_experiance', models.CharField(blank=True, max_length=90, null=True)),
                ('qualification', models.CharField(blank=True, max_length=100, null=True)),
                ('location', models.CharField(blank=True, max_length=100, null=True)),
                ('preferred_location', models.CharField(blank=True, max_length=190, null=True)),
                ('address', models.CharField(blank=True, max_length=100, null=True)),
                ('current_salary', models.CharField(blank=True, max_length=100, null=True)),
                ('expected_salary', models.CharField(blank=True, max_length=100, null=True)),
                ('notice_period', models.IntegerField(blank=True, null=True)),
                ('remark', models.CharField(blank=True, max_length=100, null=True)),
                ('industry_type', models.CharField(blank=True, max_length=100, null=True)),
                ('functional_area', models.CharField(blank=True, max_length=100, null=True)),
                ('dob', models.DateField(blank=True, null=True)),
                ('resume', models.CharField(blank=True, max_length=100, null=True)),
                ('cvhtml', models.TextField(blank=True, null=True)),
                ('ip_address', models.CharField(blank=True, max_length=100, null=True)),
                ('jobboard_url', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('pincode', models.IntegerField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'candidate_details',
                'managed': True,
                'unique_together': {('application_id', 'email', 'mobile_no')},
            },
        ),
        migrations.CreateModel(
            name='EmailTemplates',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('template_name', models.CharField(max_length=100)),
                ('template_area', models.CharField(max_length=45)),
                ('subject', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('sended_by', models.CharField(db_column='sended_by', default='passive', max_length=50)),
                ('sender_name', models.CharField(db_column='sender_name', default='Bot Shreyasi', max_length=50)),
                ('ip_address', models.CharField(default='0.0.0.0', max_length=150)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('design', models.TextField(blank=True, null=True)),
                ('added_by', models.ForeignKey(db_column='added_by', default=1, on_delete=django.db.models.deletion.CASCADE, related_name='added_email_tempalate', to=settings.AUTH_USER_MODEL)),
                ('application', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='userprofile.application')),
            ],
            options={
                'db_table': 'email_templates',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='EmailsLogs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(default=uuid.uuid4, max_length=200, unique=True)),
                ('sended_by', models.CharField(db_column='sended_by', default='noreply', max_length=50)),
                ('sended_to', models.EmailField(db_column='sended_to', max_length=50)),
                ('is_send', models.IntegerField(default=0)),
                ('is_read', models.BooleanField(default=False)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('message', models.TextField()),
                ('subject', models.CharField(max_length=500, null=True)),
                ('attachment', models.CharField(blank=True, max_length=500, null=True)),
                ('sended_cc', models.CharField(blank=True, max_length=500, null=True)),
                ('sended_bcc', models.CharField(blank=True, max_length=500, null=True)),
                ('sent_date', models.DateTimeField()),
                ('to_be_sent_date', models.DateTimeField(blank=True, null=True)),
                ('is_otp', models.IntegerField()),
                ('ip_address', models.CharField(default='0.0.0.0', max_length=150)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('sender_name', models.CharField(db_column='sender_name', default='Bot Shreyasi', max_length=50)),
                ('is_update', models.IntegerField(blank=True, null=True)),
                ('is_smtp', models.BooleanField(default=False)),
                ('added_by', models.ForeignKey(db_column='added_by', default=1, on_delete=django.db.models.deletion.CASCADE, related_name='added_email_log', to=settings.AUTH_USER_MODEL)),
                ('application', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='application_email_log', to='userprofile.application')),
                ('candidate', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='userprofile.candidatedetails')),
                ('email_template', models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, to='userprofile.emailtemplates')),
            ],
            options={
                'db_table': 'email_logs',
                'managed': True,
            },
        ),
    ]
