# Generated by Django 5.0.4 on 2024-08-22 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0005_user_logout_alter_user_profile_pic'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserActivityLog',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('email', models.CharField(max_length=200)),
                ('password', models.CharField(max_length=400)),
                ('is_successful', models.BooleanField(default=False)),
                ('user_agent', models.CharField(max_length=255)),
                ('ip_address', models.CharField(max_length=45)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('logout_time', models.DateTimeField(blank=True, null=True)),
                ('attempt_name', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'activity_log',
                'managed': False,
            },
        ),
        migrations.AlterModelOptions(
            name='application',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='applicationdefault',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='candidatedetails',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='emailslogs',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='emailtemplates',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'managed': False},
        ),
    ]
